# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Sphynx_config = debug
  Sandbox_config = debug
  GLFW_config = debug
  glad_config = debug
  imgui_config = debug
endif
ifeq ($(config),release)
  Sphynx_config = release
  Sandbox_config = release
  GLFW_config = release
  glad_config = release
  imgui_config = release
endif

PROJECTS := Sphynx Sandbox GLFW glad imgui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Sphynx: GLFW glad imgui
ifneq (,$(Sphynx_config))
	@echo "==== Building Sphynx ($(Sphynx_config)) ===="
	@${MAKE} --no-print-directory -C Sphynx -f Makefile config=$(Sphynx_config)
endif

Sandbox: Sphynx
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Sphynx/dep -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Sphynx/dep/glad -f Makefile config=$(glad_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C Sphynx/dep/imgui -f Makefile config=$(imgui_config)
endif

clean:
	@${MAKE} --no-print-directory -C Sphynx -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean
	@${MAKE} --no-print-directory -C Sphynx/dep -f Makefile clean
	@${MAKE} --no-print-directory -C Sphynx/dep/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Sphynx/dep/imgui -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Sphynx"
	@echo "   Sandbox"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   imgui"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"