externalproject "angelscript"   
    uuid "39E6AF97-6BA3-4A72-8C61-BCEBF214EBFD"   
    kind "StaticLib"   
    language "C++"
    location "angelscript/sdk/angelscript/projects/msvc2019"
    staticruntime "on"
    --I Don't know how to do this.
    -- filter "toolset:msc"
    --     location "angelscript/sdk/angelscript/projects/msvc2019"
    -- filter "toolset:gcc"
    --     location "angelscript/sdk/angelscript/projects/mingw"